### ISSUE TITLE
Any chance of rev bump and deployment of current master?

### ISSUE THREAD

**Issue by spitimage** [kevinmehall/rust-soapysdr#16]
The 0.2 release will not build with SoapySDR 0.8, but the latest changes on Master will. Are there any plans to release to support cargo builds?

**Comment by kevinmehall** [comment]
I was planning to wait until SoapySDR 0.8 gets officially released in case there are additional breaking changes.

Looking at the changes merged in #15, it looks like I should be able isolate the change in `soapysdr-sys` and release a patch version compatible with SoapySDR git master without needing to ensure both crates are upgraded together. That keeps it simpler, especially if I have to update it again for the final 0.8 release.

**Comment by kevinmehall** [comment]
Released `soapysdr-sys` 0.7.1. No update to the `soapysdr` crate needed.
