### ISSUE TITLE
macOS llvm and libc errors

### ISSUE THREAD

**Issue by JuliDi** [kevinmehall/rust-soapysdr#19]
Hi,

apparently there are linker errors when trying to compile this on macOS.
However, there seems to be a solution that I would like to share here – in case anyone else is trying the same thing:

1.  Install llvm with homebrew: `$ brew install llvm`
2. Make sure the commandline tools are installed and check whether `libclang` is available at `/Library/Developer/CommandLineTools/usr/lib/libclang.dylib`.
Running `cargo build` now unfortunately gives the following error:
```bash
error: failed to run custom build command for `soapysdr-sys v0.7.2 (/Users/<user>/rust-soapysdr/soapysdr-sys)`

Caused by:
  process didn't exit successfully: `/Users/<user>/rust-soapysdr/target/debug/build/soapysdr-sys-a03975fe81e5e189/build-script-build` (signal: 6, SIGABRT: process abort signal)
  --- stderr
  dyld: Library not loaded: @rpath/libclang.dylib
    Referenced from: /Users/<user>/rust-soapysdr/target/debug/build/soapysdr-sys-a03975fe81e5e189/build-script-build
    Reason: image not found
```
3. Build the project using `$ export DYLD_LIBRARY_PATH=/Library/Developer/CommandLineTools/usr/lib/ cargo build`

For some reason, the `clang` library can't be found automatically and we have to help the linker (see https://github.com/rust-qt/ritual/issues/75)

Hope this helps.

@kevinmehall thanks for making this project available!

**Comment by inganault** [comment]
This probably related to rust-bindgen [0.52 features changes](https://github.com/rust-lang/rust-bindgen/blob/master/CHANGELOG.md#0520). PR #20 should already fixed it, but I don't have macOS to verify.
