### ISSUE TITLE
Update Dependencies

### ISSUE THREAD

**Issue by bastibl** [kevinmehall/rust-soapysdr#25]
Thanks for your work on the crate! Recently Cargo started to warn about future incompatibilities because of outdated dependencies (in particular `bindgen` in `-sys`). Would you mind updating them and releasing a new version or do you accept PRs?

**Comment by kevinmehall** [comment]
Released soapysdr-sys 0.7.4 with the bindgen dependency updated to 0.64. This seemed to be the only dependency with a semver-incompable newer version available, but if you see anything else, a PR would be great.

**Comment by bastibl** [comment]
Perfect, thanks!
