### ISSUE TITLE
Undefined behavior in `read`

### ISSUE THREAD

**Issue by cafce25** [kevinmehall/rust-soapysdr#32]
The implementation of [`read`](https://github.com/kevinmehall/rust-soapysdr/blob/b0b1828a947572da1e1a480901a2cb2ec7c747dc/src/device.rs#L947) invokes [UB](https://doc.rust-lang.org/reference/behavior-considered-undefined.html) by using `SoapySDRDevice_readStream` to write to `buffers` which is behind a shared reference. It can probably be solved by changing the signature from `&[&mut [E]]` to `&mut [&mut [E]]` unfortunately that's a breaking change.

**Comment by kevinmehall** [comment]
Good catch, thanks for noticing. Fixed in 4d61a6416d4e9a8fb0852dc562b5904b1f285470.

Let me check if there are other breaking changes that are desirable, and I'll publish 0.4 soon.

**Comment by kevinmehall** [comment]
Released in 0.4.0
