### ISSUE TITLE
Publish on crates.io

### ISSUE THREAD

**Issue by SolidTux** [kevinmehall/rust-soapysdr#8]
Is the there a reason why this is not yet published on crates.io? It would be easier to specify as a dependency ...

**Comment by kevinmehall** [comment]
I didn't get it to a point I felt it was "done" enough to make a release, but it's definitely usable, so yeah, I'll go ahead and release 0.1. Can always release 0.2 later with a better API...

**Comment by kevinmehall** [comment]
Published https://crates.io/crates/soapysdr
